YaamirukaBayamenApp/config/routes.rb
Rails.application.routes.draw do
  root 'sambavams#index'
  get 'plot' => 'sambavams#plot'
  get 'safe_routes' => 'sambavams#safe_routes'
  get 'new' => 'sambavams#new'
  post 'sambavams', to: 'sambavams#create'
end

YaamirukaBayamenApp/app/models/location.rb
class Location
  attr_accessor :name, :latitude, :longitude, :occurences

  def initialize(options)
    self.name = options[:name]
    self.latitude = options[:latitude]
    self.longitude = options[:longitude]
    self.occurences = options[:occurences]
  end
end

YaamirukaBayamenApp/app/models/path.rb
class Path
  attr_accessor :start_point, :end_point, :occurences, :unsafe_measure, :bounds

  def initialize(options)
    self.start_point = options[:start_point]
    self.end_point = options[:end_point]
    self.bounds = options[:bounds]
    self.occurences = options[:occurences]
    self.unsafe_measure = options[:unsafe_measure]
  end
end

YaamirukaBayamenApp/app/models/sambavam.rb
class Sambavam < ClusterPoint::Document
  contains :location
end

YaamirukaBayamenApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

YaamirukaBayamenApp/app/controllers/sambavams_controller.rb
class SambavamsController < ApplicationController
  before_action :set_locations, only: [:plot, :safe_routes]

  def new
    @location = params[:name]
    @lat = params[:lat]
    @long = params[:long]
  end

  def index
  end

  def create
    doc = find_document(params[:lat], params[:long])
    doc.present? ? update_document(doc[0]) : create_document(params)
    redirect_to '/'
  end

  def plot
    render json: @locations, status: :ok
  end

  def safe_routes
    crisis_locations = locations(@locations)
    paths = []
    routes_json = routes_from_maps(request_url)
    routes_json["routes"].each do |route|
      path = construct_path(route)
      path = traverse_route(route, path, crisis_locations)
      paths << path
    end
    safe_routes = categorised_routes(paths)
    route_bounds = []
    safe_routes.each do |safe_route|
      route_bounds << {"bounds" => [{"lat" => safe_route.bounds[0]["lat"], "lng" => safe_route.bounds[0]["lng"]},
                                    {"lat" => safe_route.bounds[1]["lat"], "lng" => safe_route.bounds[1]["lng"]}]
      }
    end
    render json: route_bounds, status: :ok
  end

  private
  def find_document(lat, long)
    user = 'radhikab@thoughtworks.com'
    password = 'radhikab'
    user_id = '1201'
    url = "https://api-eu.clusterpoint.com/#{user_id}/YaamirukaBayamenProd/_search.json"
    resource = RestClient::Resource.new(url, user: user, password: password)
    payload = {'query' => "<lat>#{lat}</lat><long>#{long}</long>"}
    response = resource.post(payload.to_json)
    JSON.parse(response.body)['documents']
  end

  def update_document(doc)
    user = 'radhikab@thoughtworks.com'
    password = 'radhikab'
    user_id = '1201'
    cluster_url = "https://api-eu.clusterpoint.com/#{user_id}/YaamirukaBayamenProd/.json"
    resource = RestClient::Resource.new(cluster_url, user: user, password: password)
    payload = {'id' => doc['id'], 'occurences' => doc['occurences'].to_i + 1}.to_json
    response = resource.post(payload)
    response.body
  end

  def create_document(params)
    user = 'radhikab@thoughtworks.com'
    password = 'radhikab'
    user_id = '1201'
    cluster_url = "https://api-eu.clusterpoint.com/#{user_id}/YaamirukaBayamenProd/.json"
    resource = RestClient::Resource.new(cluster_url, user: user, password: password)
    payload = {'id' => Time.now, 'lat' => params[:lat], 'long' => params[:long], 'name' => params[:name], 'occurences' => 1, 'source' => 'user'}.to_json
    response = resource.post(payload)
    response.body
  end

  def set_locations
    params = '{"query":"*","docs":"100"}'
    user = 'radhikab@thoughtworks.com'
    password = 'radhikab'
    user_id = '1201'
    fetch_url = "https://api-eu.clusterpoint.com/#{user_id}/YaamirukaBayamenProd/_search.json"
    @locations = locations_from_cluster(params, fetch_url, user, password)
  end

  def locations_from_cluster(payload, cluster_url, username, password)
    resource = RestClient::Resource.new(cluster_url, user: username, password: password)
    response = resource.post(payload)
    response.body
  end

  def locations(locations_json)
    locations = []
    locations_json = JSON.parse(locations_json)
    locations_json["documents"].each do |location|
      locations << Location.new(name: location["name"], latitude: location["lat"].to_f, longitude: location["long"].to_f, occurences: location["occurences"].to_i)
    end if locations_json["documents"].present?
    locations
  end

  def init_safe_route_path
    origin = 'Alandur,IN'
    destination = 'Adyar,IN'
    [origin, destination]
  end

  def request_url
    api_key = 'AIzaSyAYU_fYcPQGp1FnLfH4W0F07hofMQkvZcQ'
    origin, destination = init_safe_route_path
    alternative_routes = true
    "https://maps.googleapis.com/maps/api/directions/json?origin=#{origin}&destination=#{destination}&alternatives=#{alternative_routes}&key=#{api_key}"
  end

  def routes_from_maps(url)
    resource = RestClient::Resource.new(url)
    response = resource.get
    JSON.parse(response.body)
  end

  def construct_path(route)
    origin, destination = init_safe_route_path
    ne_bound = route["bounds"]["northeast"]
    sw_bound = route["bounds"]["southwest"]
    Path.new(start_point: origin, end_point: destination, occurences: 0, unsafe_measure: 0, bounds: [ne_bound, sw_bound])
  end

  def update_path(crisis_locations, path, latitude, longitude)
    matching_crisis_locations = crisis_locations.select { |loc| loc.latitude == latitude && loc.longitude == longitude }
    if matching_crisis_locations.present?
      path.occurences += 1
      path.unsafe_measure += matching_crisis_locations.first.occurences.to_i
    end
    path
  end

  def traverse_route(route, path, crisis_locations)
    points = []
    route["legs"].each do |leg|
      leg["steps"].each do |step|
        start_point_lat = step["start_location"]["lat"]
        start_point_long = step["start_location"]["lng"]
        path = update_path(crisis_locations, path, start_point_lat, start_point_long) unless points.include?([start_point_lat,start_point_long])
        points << [start_point_lat, start_point_long]
        end_point_lat = step["end_location"]["lat"]
        end_point_long = step["end_location"]["lng"]
        path = update_path(crisis_locations, path, end_point_lat, end_point_long) unless points.include?([end_point_lat,end_point_long])
        points << [end_point_lat, end_point_long]
      end
    end
    path
  end

  def categorised_routes(paths)
    minimum_occurrence = paths.collect(&:occurences).min
    minimum_unsafe_measure = paths.collect(&:unsafe_measure).min
    min_occurrence_route = paths.select {|path| path.occurences == minimum_occurrence}.first
    min_unsafe_route = paths.select {|path| path.unsafe_measure == minimum_unsafe_measure}.first
    [min_occurrence_route,min_unsafe_route]
  end
end

YaamirukaBayamenApp/app/helpers/application_helper.rb
module ApplicationHelper
end

YaamirukaBayamenApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yaamiruka Bayamen App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.css" />
  <script src="http://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
</head>
<body>

<%= yield %>

</body>
</html>

YaamirukaBayamenApp/app/views/sambavams/new.html.erb
<div class="container col-xs-6 vertical-align">
  <h2>Add a new incident</h2>

<%= form_tag sambavams_path do %>
    <%= hidden_field_tag :lat, @lat %>
    <%= hidden_field_tag :long, @long %>

    <div class="form-group">
      <%= label_tag :name, 'Location' %>
      <%= text_field_tag :name, @location, readonly: true, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= label_tag :names, 'Suspect Name/Alias' %>
      <%= text_field_tag :names, '', class:"form-control" %>
    </div>

    <div class="form-group">
      <%= label_tag :height, 'Height(in inches)' %>
      <%= text_field_tag :height, '',class:"form-control" %>
    </div>

    <div class="form-group">
      <%= label_tag :hair_style, 'Hair Style' %>
      <%= select_tag :hair_style, options_for_select(['Unsure','Short','Medium','Long','Bald/Shaved']), class:"form-control" %>
    </div>

    <div class="form-group">
      <%= label_tag :eye_colour, 'Eye Colour' %>
      <%= select_tag :eye_colour, options_for_select(['Unsure','Blue','Brown','Black','Grey']), class:"form-control" %>
    </div>

    <div class="form-group">
      <%= label_tag :crime_description, 'Crime Description' %>
      <%= text_area_tag :crime_description, '' , class:"form-control"%>
    </div>

    <div class="form-group">
      <%= submit_tag "Submit Tip", class: "btn btn-success" %>
      <%= link_to 'Home', root_path, class: "btn btn-primary" %>
    </div>

<% end %>

</div>